name: Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GKE_CLUSTER: CHANGEME
  GKE_ZONE: CHANGEME

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    - name: Configure Docker
      run: |-
        gcloud --quiet auth configure-docker

    # Get the GKE credentials so we can deploy to the cluster
    - name: Get GKE cluster credentials
      run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Deploy to GKE
      run: |-
        kubectl apply -f manifest.yaml
